namespace DAL.Models
{
    public class IndustriesList
    {
        public static readonly List<string> Industries = new()
        {
            "Aerospace",
            "Agricultural",
            "Automotive",
            "Basic metal",
            "Chemical",
            "Computer",
            "Construction",
            "Creative",
            "Cultural",
            "Defense",
            "Education",
            "Electric power",
            "Electronics",
            "Energy",
            "Engineering",
            "Entertainment",
            "Farming",
            "Fashion",
            "Film",
            "Financial services",
            "Fishing",
            "Food",
            "Forestry",
            "Gambling",
            "Gas",
            "Green",
            "Health services",
            "Hospitality",
            "Hotels",
            "Industrial robot",
            "Information",
            "Information technology",
            "Infrastructure",
            "Insurance",
            "Leisure",
            "Low technology",
            "Manufacturing",
            "Meat",
            "Media",
            "Merchandising",
            "Mining",
            "Music",
            "News media",
            "Oil and gas",
            "Pharmaceutical",
            "Professional",
            "Publishing",
            "Pulp and paper",
            "Railway",
            "Real estate",
            "Retail",
            "Scientific",
            "Services",
            "Software",
            "Space",
            "Sport",
            "Steel",
            "Technology",
            "Telecommunications",
            "Textile",
            "Tobacco",
            "Transport",
            "Utility",
            "Video game",
            "Water",
            "Wholesale",
            "Wood"
        };
    }
}
